### ISSUE TITLE
Suggestion to alleviate colonists drowning surrounding some structures that incorporate water

### ISSUE THREAD

**Issue by mopsyd** [ldtteam/minecolonies-features#653]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: [minecolonies-1.18.1-1.0.428-RELEASE.jar](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3642043)
- Related Mods and their Versions: Minecolonies (all versions I have played)

## Is your feature request related to a problem?

This is related to colonists drowning themselves, which has been a lonstanding issue in some specific cases. I am proposing a low-impact solution to alleviate this issue to some degree without the need for complex AI patches or revising structure schematics.

Various structures that incorporate water into their design or are intended to be placed alongside bodies of water frequently result in colonists swimming underneath portions of their layout and drowning. Examples include fisherman huts and the medieval spruce sawmill (the one with the water  wheel). 

- Workers at these buildings frequently drown when they are wandering around their job plot.
- Builders building these buildings frequently drown, or block in nearby colonists who then drown during the build process.
- Visitors wandering around the colony drown themselves, then penalize the player with the dangerous place warning which is entirely outside player control in this case.

## Enhancement or Change description

I am proposing a very simple check that will teleport drowning colonists who are stuck back to their hut block (or the inn if they are a visitor) in a couple very specific circumstances.

If _all of the following are true:_

- The colonist has taken at least three ticks of drown damage
- The colonist has not taken damage from any other source aside from drowning for at least two seconds
- The colonist is not currently targeted by any hostile mob
- There is not an active raid
- The colonist _is not_ being pushed horizontally by running water (being pushed downward/upward should not trigger this condition)

And _at least one of the following is true:_

- The colonist is submerged and has an ice block over their head (meaning they swam under an ice sheet and will absolutely drown in all other circumstances)
- The colonist has not moved from their current x/y/z position for at least two drown damage ticks (with a margin of error of a half meter)
- The colonist has no viable pathfinding route away from a drowning scenario (covers some rare cases where a colonist is automatically moved to their plot, and placed somewhere lethal like inside their waterwheel, in the case of the sawmill mentioned previously).

Then the following will happen (in order, only one of whichever applies first):
- If the colonist is a builder, they will be teleported to their build hut and their build step iteration recalculated
- If the colonist is a worker, they will be teleported to their hut block
- If the colonist is unemployed, they will be teleported to their house
- If the colonist is homeless, they will be teleported to the town hall
- If the colonist is a visitor, they will either be teleported to the nearest inn/town hall (whichever is appropriate), or silently discarded/respawned normally (eg: if you rescued a zombie villager and don't even have an inn for them to warp to)

And optionally:

- Log the event
- Display a message for the player in chat if debug is enabled to help diagnose the problem or respond with an in-game solution if it is happening repetitively

### Notes or related things

This addresses the majority of unintentional drowning scenarios without negating the possibility of drowning in combat situations, raids, or players not putting any work into making the terrain safe (like waterfalls into ravines nearby, which should absolutely still drown colonists that pathfind through them). This is intended to be a reasonably simple and pragmatic answer to a consistent problem with minimal development overhead to address, as well as not requiring asset redesign or unintended end user consequences.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by anonymous563** [comment]
That's not the latest version. This was fixed.

**Comment by mopsyd** [comment]
I tested it in the current alpha also. It still happens. I do not play ongoing in bleeding edge alphas, I just verify whether issues were fixed or not and otherwise play normally in stable releases. Carpenters still drown in both.

**Comment by anonymous563** [comment]
Ah, fair enough.

As a note though (from the Discord):

> MineColonies doesn't use the traditional classifications (alpha, beta, release) as the entire mod can be considered in a beta state (just based on the number of features still planned). However, Curseforge limits the number of releases and betas we can push out, and due to the devs' speed, the latest version will most often be an alpha. One classification is as stable as the others, so always get the latest version of MineColonies, regardless of its classification.

**Comment by mopsyd** [comment]
Yea I get that. But there is also a reason this is a feature request and not a bug report. The underlying minecraft engine is terrible at entities understanding their relationship with water. Things that shouldn't be in it drown frequently, and things that should be in it beach themselves and die. This is a limitation of the game itself, not a responsibility of a mod author. However, we do have to come up with clever workarounds now and then to harden how our content is affected by it until the mojang team offers a more elegant answer through the AI itself. Hence the feature request. This is not intended to fix the problem entirely, just make it not affect minecolonies in adverse ways too incredibly much.
